config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    flash[:success] = "Article has been created"
    redirect_to articles_path
  end
  

  protected

  def article_params
    params.require(:article).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h3 class="text-center">Adding new Article</h3>

<div class="row">
	<div class="col-md-12">
		<%= form_for @article, html: {class: 'form-horizontal', role: 'form'} do |f| %>
			<div class="form-group">
				<div class="control-label col-md-1">
					<%= f.label :title %>
				</div>
				<div class="col-md-11">
					<%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %>
				</div>
			</div>

			<div class="form-group">
				<div class="control-label col-md-1">
					<%= f.label :body %>
				</div>
				<div class="col-md-11">
					<%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Body of Article" %>
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-1 col-md-11">
					<%= f.submit class: "btn btn-primary btn-lg pull-right" %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header role="banner">
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collpase-1">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to  "Blog App", root_path, class: 'navbar-brand' %>
          </div>
          <div class="navbar-collpase collpase" id="bs-example-navbar-collpase-1">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to  "Authors", '#' %></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |key, message| %>
            <div class="text-center alert alert-<%=key == 'notice' ? 'success' : 'danger' %>">
              <%= message %>
            </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>